# Generated by Django 4.2.11 on 2024-06-28 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='unique_tag',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
