# Generated by Django 4.2.11 on 2024-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_pdffile_unique_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffile",
            name="translated_html",
            field=models.FileField(blank=True, null=True, upload_to="translated_html/"),
        ),
    ]
